# Generated by Django 3.1 on 2022-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя заказчика', max_length=20, verbose_name='Имя заказчика')),
                ('second_name', models.CharField(help_text='Фамилия заказчика', max_length=20, verbose_name='Фамилия заказчика')),
                ('email', models.EmailField(help_text='Фамилия заказчика', max_length=20, verbose_name='E-mail заказчика')),
                ('comment', models.TextField(help_text='Комментарий', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
