# Generated by Django 2.2 on 2022-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, help_text='Телефон заказчика', max_length=20, verbose_name='Телефон заказчика'),
            preserve_default=False,
        ),
    ]
