# Generated by Django 3.1 on 2022-04-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id'], 'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['id'], 'verbose_name': 'Подтопик', 'verbose_name_plural': 'Подтопики'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id'], 'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
    ]
