# Generated by Django 2.2 on 2022-04-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_auto_20220427_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок абзаца', verbose_name='Заголовок абзаца')),
                ('message', models.TextField(help_text='Абзац', verbose_name='Абзац')),
                ('image', models.ImageField(upload_to='subtopic_pics/', verbose_name='Картинка')),
                ('topic', models.ForeignKey(help_text='Топик', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='attraction.Topic', verbose_name='Топик')),
            ],
        ),
    ]
