# Generated by Django 3.1 on 2022-04-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
