# Generated by Django 2.2 on 2022-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_auto_20220427_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetopic',
            options={'ordering': ['id'], 'verbose_name': 'Абзац топика', 'verbose_name_plural': '  Абзацы топиков'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id'], 'verbose_name': 'Топик', 'verbose_name_plural': '   Топики'},
        ),
        migrations.AlterField(
            model_name='messagesubtopic',
            name='message',
            field=models.TextField(help_text='Абзац подтопика', verbose_name='Абзац подтопика'),
        ),
        migrations.AlterField(
            model_name='messagetopic',
            name='message',
            field=models.TextField(help_text='Абзац топика', verbose_name='Абзац топика'),
        ),
    ]
