# Generated by Django 2.2 on 2022-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_auto_20220427_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesubtopic',
            name='message',
            field=models.TextField(blank=True, help_text='Абзац подтопика', verbose_name='Абзац подтопика'),
        ),
        migrations.AlterField(
            model_name='messagetopic',
            name='message',
            field=models.TextField(blank=True, help_text='Абзац топика', verbose_name='Абзац топика'),
        ),
    ]
