# Generated by Django 2.2 on 2022-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0006_auto_20220427_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок на главной странице', verbose_name='Заголовок на главной странице')),
                ('message', models.TextField(blank=True, help_text='Абзац на главной странице', verbose_name='Абзац на главной странице')),
                ('image', models.ImageField(blank=True, upload_to='main_pics/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Абзац главной страницы',
                'verbose_name_plural': '   Абзацы главной страницы',
                'ordering': ['id'],
            },
        ),
    ]
