# Generated by Django 2.2 on 2022-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0007_messagemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг', verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг', verbose_name='Слаг'),
        ),
    ]
