# Generated by Django 2.2 on 2022-04-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0009_auto_20220428_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(help_text='Топик', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='attraction.Topic', verbose_name='Топик'),
        ),
    ]
