# Generated by Django 2.2 on 2022-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0010_auto_20220428_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(help_text='Слаг', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(help_text='Слаг', unique=True, verbose_name='Слаг'),
        ),
    ]
