# Generated by Django 2.2 on 2022-05-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0011_auto_20220428_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetopic',
            options={},
        ),
    ]
