# Generated by Django 2.2 on 2022-05-28 18:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0012_auto_20220528_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='topic_pics/', verbose_name='Картинка'),
        ),
    ]
