# Generated by Django 2.2 on 2022-05-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0013_auto_20220528_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesubtopic',
            options={'ordering': ['id'], 'verbose_name': 'Абзац подтопика', 'verbose_name_plural': 'Абзацы подтопиков'},
        ),
        migrations.AlterModelOptions(
            name='messagetopic',
            options={'ordering': ['id'], 'verbose_name': 'Абзац топика', 'verbose_name_plural': '  Абзацы топиков'},
        ),
    ]
