# Generated by Django 2.2 on 2022-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0014_auto_20220529_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(help_text='Название подтопика', max_length=50, verbose_name='Название подтопика'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Название топика', max_length=50, verbose_name='Название топика'),
        ),
    ]
