# Generated by Django 2.2 on 2022-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0015_auto_20220530_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(help_text='Стоимость мишени', verbose_name='Стоимость мишени')),
                ('darts', models.IntegerField(help_text='Стоимость набора дротиков', verbose_name='Стоимость набора дротиков')),
                ('balls', models.IntegerField(help_text='Стоимость набора шаров', verbose_name='Стоимость набора шаров')),
                ('pump', models.IntegerField(help_text='Стоимость насоса', verbose_name='Стоимость насоса')),
                ('prize_set', models.IntegerField(help_text='Стоимость запаса призов', verbose_name='Стоимость запаса призов')),
                ('price_hol', models.IntegerField(help_text='Стоимость билета в праздники', verbose_name='Цена билета в праздники')),
                ('price_us', models.IntegerField(help_text='Стоимость билета в обычный день', verbose_name='Цена билета в обычный день')),
                ('price_z', models.IntegerField(help_text='Стоимость билета в плохой день', verbose_name='Цена билета в плохой день')),
                ('tickets_hol', models.IntegerField(help_text='Количество билетов в праздники', verbose_name='Количество билетов в праздники')),
                ('tickets_us', models.IntegerField(help_text='Количество билетов в обычный день', verbose_name='Количество билетов в обычный день')),
                ('tickets_z', models.IntegerField(help_text='Количество билетов в плохой день', verbose_name='Количество билетов в плохой день')),
                ('balls_per_play', models.IntegerField(help_text='Количество шаров на игру', verbose_name='Количество шаров на игру')),
                ('small_prize_rate', models.IntegerField(help_text='% маленьких призов на 100 игр', verbose_name='% маленьких призов на 100 игр')),
                ('medium_prize_rate', models.IntegerField(help_text='% средних призов на 100 игр', verbose_name='% средних призов на 100 игр')),
                ('big_prize_rate', models.IntegerField(help_text='% больших призов на 100 игр', verbose_name='% больших призов на 100 игр')),
                ('operator_fix', models.IntegerField(help_text='Фикс. ставка оператора в день', verbose_name='Фикс. ставка оператора в день')),
                ('operator_share', models.DecimalField(decimal_places=2, help_text='Доля от выручки оператора', max_digits=3, verbose_name='Доля от выручки оператора')),
            ],
        ),
    ]
