# Generated by Django 2.2 on 2022-06-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0016_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemain',
            options={'ordering': ['id'], 'verbose_name': 'Абзац главной страницы', 'verbose_name_plural': '    Абзацы главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='messagesubtopic',
            options={'ordering': ['id'], 'verbose_name': 'Абзац подтопика', 'verbose_name_plural': ' Абзацы подтопиков'},
        ),
        migrations.AlterModelOptions(
            name='messagetopic',
            options={'ordering': ['id'], 'verbose_name': 'Абзац топика', 'verbose_name_plural': '   Абзацы топиков'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'ordering': ['id'], 'verbose_name': 'Набор параметров для расчета', 'verbose_name_plural': 'Наборы параметров для расчета'},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['id'], 'verbose_name': 'Подтопик', 'verbose_name_plural': '  Подтопики'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id'], 'verbose_name': 'Топик', 'verbose_name_plural': '    Топики'},
        ),
    ]
