# Generated by Django 2.2 on 2022-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0017_auto_20220618_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='balls',
            field=models.IntegerField(help_text='руб.', verbose_name='Стоимость набора шаров'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='balls_per_play',
            field=models.IntegerField(help_text='шт.', verbose_name='Количество шаров на игру'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='big_prize_rate',
            field=models.IntegerField(help_text='шт. на 100 игр', verbose_name='% больших призов на 100 игр'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='darts',
            field=models.IntegerField(help_text='руб.', verbose_name='Стоимость набора дротиков'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='medium_prize_rate',
            field=models.IntegerField(help_text='шт. на 100 игр', verbose_name='% средних призов на 100 игр'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='operator_fix',
            field=models.IntegerField(help_text='руб.', verbose_name='Фикс. ставка оператора в день'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='operator_share',
            field=models.DecimalField(decimal_places=2, help_text='доля', max_digits=3, verbose_name='Доля от выручки оператора'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='price_hol',
            field=models.IntegerField(help_text='руб.', verbose_name='Цена билета в праздники'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='price_us',
            field=models.IntegerField(help_text='руб.', verbose_name='Цена билета в обычный день'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='price_z',
            field=models.IntegerField(help_text='руб.', verbose_name='Цена билета в плохой день'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='prize_set',
            field=models.IntegerField(help_text='руб.', verbose_name='Стоимость запаса призов'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='pump',
            field=models.IntegerField(help_text='руб.', verbose_name='Стоимость насоса'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='small_prize_rate',
            field=models.IntegerField(help_text='шт. на 100 игр', verbose_name='% маленьких призов на 100 игр'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='target',
            field=models.IntegerField(help_text='руб.', verbose_name='Стоимость мишени'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='tickets_hol',
            field=models.IntegerField(help_text='шт.', verbose_name='Количество билетов в праздники'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='tickets_us',
            field=models.IntegerField(help_text='шт.', verbose_name='Количество билетов в обычный день'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='tickets_z',
            field=models.IntegerField(help_text='шт.', verbose_name='Количество билетов в плохой день'),
        ),
    ]
