# Generated by Django 2.2 on 2022-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0018_auto_20220618_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='big_prize_price',
            field=models.IntegerField(default=0, help_text='цена большого приза', verbose_name='цена большого приза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='medium_prize_price',
            field=models.IntegerField(default=1, help_text='цена среднего приза', verbose_name='цена среднего приза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='small_prize_price',
            field=models.IntegerField(default=1, help_text='цена маленького приза', verbose_name='цена маленького приза'),
            preserve_default=False,
        ),
    ]
