# Generated by Django 2.2 on 2022-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0019_auto_20220619_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='holidays',
            field=models.IntegerField(default=0, help_text='дней', verbose_name='Число праздников и выходных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='leasing',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Аренда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='leasing1st',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Аванс аренды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='months',
            field=models.IntegerField(default=0, help_text='мес.', verbose_name='Число месяцев'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='warm_days',
            field=models.IntegerField(default=0, help_text='дней', verbose_name='Число темлых дней'),
            preserve_default=False,
        ),
    ]
