# Generated by Django 2.2 on 2022-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0020_auto_20220619_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='bass',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Стоимость бассейна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='num_rybok',
            field=models.IntegerField(default=0, help_text='шт.', verbose_name='Число муляжей рыбки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='num_ved',
            field=models.IntegerField(default=0, help_text='шт.', verbose_name='Число ведерок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='rybka',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Цена муляжа рыбки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='tehn',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Тех. обслуживание в мес.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='ved',
            field=models.IntegerField(default=0, help_text='руб.', verbose_name='Цена ведерка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameters',
            name='warm_days',
            field=models.IntegerField(help_text='дней', verbose_name='Число теплых дней'),
        ),
    ]
